activation: ReLU
alias: null
batch_size: 7
dataloader_kwargs: null
drop_last_loader: false
dropout_prob_theta: 0.0
early_stop_patience_steps: -1
exclude_insample_y: false
futr_exog_list: null
h: 60
hist_exog_list: null
inference_windows_batch_size: -1
input_size: 300
interpolation_mode: linear
learning_rate: 0.001
loss: &id001 !!python/object:neuralforecast.losses.pytorch.MAE
  _backward_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _backward_pre_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _buffers: !!python/object/apply:collections.OrderedDict
  - []
  _forward_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _forward_hooks_always_called: !!python/object/apply:collections.OrderedDict
  - []
  _forward_hooks_with_kwargs: !!python/object/apply:collections.OrderedDict
  - []
  _forward_pre_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _forward_pre_hooks_with_kwargs: !!python/object/apply:collections.OrderedDict
  - []
  _is_full_backward_hook: null
  _load_state_dict_post_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _load_state_dict_pre_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _modules: !!python/object/apply:collections.OrderedDict
  - []
  _non_persistent_buffers_set: !!set {}
  _parameters: !!python/object/apply:collections.OrderedDict
  - []
  _state_dict_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _state_dict_pre_hooks: !!python/object/apply:collections.OrderedDict
  - []
  horizon_weight: !!python/object/apply:torch._utils._rebuild_tensor_v2
  - !!python/object/apply:torch.storage._load_from_bytes
    - !!binary |
      gAKKCmz8nEb5IGqoUBkugAJN6QMugAJ9cQAoWBAAAABwcm90b2NvbF92ZXJzaW9ucQFN6QNYDQAA
      AGxpdHRsZV9lbmRpYW5xAohYCgAAAHR5cGVfc2l6ZXNxA31xBChYBQAAAHNob3J0cQVLAlgDAAAA
      aW50cQZLBFgEAAAAbG9uZ3EHSwR1dS6AAihYBwAAAHN0b3JhZ2VxAGN0b3JjaApGbG9hdFN0b3Jh
      Z2UKcQFYCwAAADEzNjA0ODgwNjQwcQJYAwAAAGNwdXEDSzxOdHEEUS6AAl1xAFgLAAAAMTM2MDQ4
      ODA2NDBxAWEuPAAAAAAAAAAAAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/
      AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8A
      AIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAA
      gD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACA
      PwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8=
  - 0
  - !!python/tuple
    - 60
  - !!python/tuple
    - 1
  - false
  - !!python/object/apply:collections.OrderedDict
    - []
  is_distribution_output: false
  output_names:
  - ''
  outputsize_multiplier: 1
  training: false
lr_scheduler: null
lr_scheduler_kwargs: null
max_steps: 1000
mlp_units:
- - 512
  - 512
- - 512
  - 512
- - 512
  - 512
n_blocks:
- 1
- 1
- 1
n_freq_downsample:
- 24
- 12
- 1
n_pool_kernel_size:
- 2
- 2
- 2
num_lr_decays: 3
num_workers_loader: 0
optimizer: null
optimizer_kwargs: null
pooling_mode: MaxPool1d
random_seed: 7
scaler_type: identity
stack_types:
- identity
- identity
- identity
start_padding_enabled: false
stat_exog_list: null
step_size: 1
val_check_steps: 100
valid_batch_size: null
valid_loss: *id001
windows_batch_size: 256
